### ISSUE TITLE
The urls in coco-en-2-mini are unreachable

### ISSUE THREAD

**Issue by TristaCheng2018** [modelscope/ms-swift#2596]
The images in public datasets are unreachable.
![0zm4f12000h4a3quc0B99](https://github.com/user-attachments/assets/1ddf22df-1e07-4723-9010-7f39af2a9475)

,uniq_id,image_id,caption,image
0,258768,11195,A snow skier assessing the mountain before starting to sky,https://xingchen-data.oss-cn-zhangjiakou.aliyuncs.com/coco/2014/train2014/COCO_train2014_000000011195.jpg
1,725439,367065,a guy that is brushing his teeth and a baby too,https://xingchen-data.oss-cn-zhangjiakou.aliyuncs.com/coco/2014/train2014/COCO_train2014_000000367065.jpg
2,580123,213997,A chair and a fireplace in a room.,https://xingchen-data.oss-cn-zhangjiakou.aliyuncs.com/coco/2014/train2014/COCO_train2014_000000213997.jpg
3,283575,370736,A red street sign showing Volt street and Mill street.,https://xingchen-data.oss-cn-zhangjiakou.aliyuncs.com/coco/2014/train2014/COCO_train2014_000000370736.jpg
4,392682,524048,A young man standing next to a pile of pallets.,https://xingchen-data.oss-cn-zhangjiakou.aliyuncs.com/coco/2014/train2014/COCO_train2014_000000524048.jpg
5,154143,427137,Some sheep walking in the field and having some fun.,https://xingchen-data.oss-cn-zhangjiakou.aliyuncs.com/coco/2014/train2014/COCO_train2014_000000427137.jpg
6,142231,579907,"A living room complete with couches, television, and fireplace.",https://xingchen-data.oss-cn-zhangjiakou.aliyuncs.com/coco/2014/train2014/COCO_train2014_000000579907.jpg
7,569327,45468,a bath room with a toilet and a sink and a pile of trash,https://xingchen-data.oss-cn-zhangjiakou.aliyuncs.com/coco/2014/train2014/COCO_train2014_000000045468.jpg
8,434237,35230,Two pizza's salad's and drinks on a table with plates.,https://xingchen-data.oss-cn-zhangjiakou.aliyuncs.com/coco/2014/train2014/COCO_train2014_000000035230.jpg

**Comment by Jintao-Huang** [comment]
Yes, it is under repair.

**Comment by Jintao-Huang** [comment]
fixed

**Comment by TristaCheng2018** [comment]
![image](https://github.com/user-attachments/assets/6877728a-a86d-487c-a5d3-734efff13cdf)
Sorry, this issue remains unresolved.
