### ISSUE TITLE
Qwen3-Omni使用deepspeed zero2 失败

### ISSUE THREAD

**Issue by jjdaxigua** [modelscope/ms-swift#6171]
**Describe the bug**
多机多卡时，使用deepspeed zero2时会卡在train阶段，然后报错NCCL超时。不使用deepspeed可以正常运行

运行命令
swift sft \
--model models/Qwen3-Omni-30B-A3B-Instruct \
--dataset dataset.parquet \
--train_type lora  \
--lora_rank 8  \
--lora_alpha 32  \
--torch_dtype bfloat16  \
--num_train_epochs 1  \
--learning_rate 1e-5  \
--target_modules all-linear \
--freeze_vit true  \
--gradient_accumulation_steps 8 \
--per_device_train_batch_size 1 \
--save_total_limit 5 \
--max_length 16384 \
--output_dir output/qwen3_omni_sft \
--warmup_ratio 0.05  \
--dataloader_num_workers 5  \
--dataset_num_proc 1 \
--gradient_checkpointing_kwargs '{"use_reentrant": false}'  \
--eval_steps 1000 \
--save_steps 1000 \
--logging_steps 5 \
--deepspeed zero2

**Comment by hjh0119** [comment]
Is the dataset multimodal (e.g., combining pure text with images/audio)?

**Comment by jjdaxigua** [comment]
@hjh0119 是的，图文数据

**Comment by jjdaxigua** [comment]
@Jintao-Huang @hjh0119 我观察py-spy卡在了 copy_grads_in_partition (deepspeed/runtime/zero/stage_1_and_2.py:1450) 
这是兼容问题吗还是什么导致的

**Comment by Jintao-Huang** [comment]
The main branch supports running Qwen3-VL; for Omni, you can currently use the device_map approach.

Refer to the examples in examples/models. This issue will be fixed later.

https://github.com/modelscope/ms-swift/pull/6161

**Comment by hjh0119** [comment]
Mixed-modal training requires additional support; you can temporarily use single-modal training instead

**Comment by Jintao-Huang** [comment]
try: https://github.com/modelscope/ms-swift/blob/main/examples/models/qwen3_omni/transformers.sh

**Comment by jjdaxigua** [comment]
@Jintao-Huang  device_map can run ，Adding the parameter **--deepspeed zero2** will nccl time out

<img width="1931" height="686" alt="Image" src="https://github.com/user-attachments/assets/7ffab582-197e-4a98-9855-aa11e763bcc0" />

**Comment by Jintao-Huang** [comment]
It will be fixed today, please wait.

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/ms-swift/pull/6196

**Comment by Jintao-Huang** [comment]
https://github.com/huggingface/transformers/issues/41680

**Comment by Jintao-Huang** [comment]
fixed. use main branch

**Comment by jjdaxigua** [comment]
@Jintao-Huang very thanks. But I test deepspeed zero3 can run, zero2 and zero1 still cannot.

**Comment by Jintao-Huang** [comment]
What's the error? Is it OOM?

Could you please provide a screenshot?

**Comment by jjdaxigua** [comment]
@Jintao-Huang Same as above, nccl timeout.

<img width="2007" height="789" alt="Image" src="https://github.com/user-attachments/assets/3d65d24f-c48f-4a1c-865c-d76a906eb69a" />

**Comment by Jintao-Huang** [comment]
This issue does indeed exist. It looks like mixed training with audio data is causing Zero2 to hang. But Zero3 can run normally...

**Comment by jjdaxigua** [comment]
I only used image and text data.

**Comment by yikun2019** [comment]
@Jintao-Huang 我也遇到了相同的问题，你可以看看问题是不是
https://zhuanlan.zhihu.com/p/1966923480290263131 这个里面提到的原因导致的
